### ISSUE TITLE
Infinite Layout -> allow to skip part of the content when no enough space (e.g. show only text that fits within the constrained container)

### ISSUE THREAD

**Issue by marcianobandeira** [QuestPDF/QuestPDF#51] opened 2021-11-04 19:16 UTC
Hello

I'm upgraded from version 2021.9.3 to 2021.10.1. In this version, ocurs 
"QuestPDF.Drawing.Exceptions.DocumentLayoutException: Composed layout generates infinite document"

In old version, works!

I understand that this is problem from my code, wich, exceeds the limit of some container, but, debug this is complex, because the architeture of code this library, in lambda expressions, don't permit debug point of bug.

Whats sugestions for locate the problem?

Thanks

**Comment by MarcinZiabek** [comment] 2021-11-04 20:12
Hello @marcianobandeira,

Thank you for your message. I am very sorry for the fact it stopped working. `Currently, a good approach to find a root cause is to start commenting out pieces of code (parts of the PDF report) and try to locate the potential issue. Once it starts rendering again, you know what is the problem.` If you provide any code examples, I will be more than happy to help. I am slightly worried that this may be a bug of the old version / or a bug introduced in the newest version. 

You can also make a try with 2021.11-beta-3 which will be deployed next week. It would be great to understand the case and, if needed, fix the problem before the 2021.11 release.

I also understand the pain of debugging this particular type of exception. For the 2021.12 December update, I am preparing a huge upgrade that will help in this debugging process and significantly reduce the pain. It will be something similar to stack traces in code debugging, in this case, it will be, what I call, an element trace. It is still in the experimental branch but I am quite close to completing it :)

**Comment by MarcinZiabek** [comment] 2021-11-04 20:25
This is just a free thought... In QuestPDF 2021.10, I refactored text drawing functionality. Now, it uses more font-related features and metrics. Previously, they have been only assumed based on some heuristics, now they are extracted from the font itself. As a result, by default, some text may take more space than previously. If you have any containers with very limited space (e.g. constrained in the layout), this may be a good area to investigate. 

Again, a good approach at this point is to start commenting out code as long as you have a working report. And this should help with indicating what is wrong. I know it is painful, I promise it will be way better soon :)

**Comment by marcianobandeira** [comment] 2021-11-04 20:54
Hello @MarcinZiabek 

thanks for always being so thoughtful!
I was tweaking some containers and my code started working again with the current version of the library.
It is not always possible to control the necessary height of a container that will receive a text, as this text is dynamic, would it be possible to implement a cut in the content in case it exceeds the size of the container?

Thanks

**Comment by MarcinZiabek** [comment] 2021-11-04 21:08
Hmm, would you like to hide some of the text if it does not fit?

**Comment by marcianobandeira** [comment] 2021-11-05 19:33
isso mesmo. digamos que eu tenha um container de 100 de largura e 50 de altura. Caso o texto ultrapasse a largura ele quebra a linha, conforme ja acontece hoje. Ao ultrapassar a altura, ele seja cortado.

**Comment by marcianobandeira** [comment] 2021-11-05 19:33
that's right. let's say I have a container 100 wide and 50 high. If the text exceeds the width, it breaks the line, as it already happens today. When exceeding the height, it is cut.

**Comment by MarcinZiabek** [comment] 2021-11-09 14:33
I will think about such a use case. So far, I always thought that people want always to display everything. Cutting content (e.g. showing only part of the text) is very specific to webpage development which is way more dynamic / needs to be responsive. Can you please think in which scenarios such a feature may come handy? How it should work from the design perspective?

**Comment by marcianobandeira** [comment] 2021-11-09 17:21
Hello @MarcinZiabek 

in a print of sales order for example, it is not necessary to print the full product name as it would require a lot of paper. Usually prints part of the name. Management reports of enterprise are a good example.
On the other hand, the printing of a contract would not admit this cut, so it would be good if the behavior was explicitly indicated by the developer.

Thanks

**Comment by MarcinZiabek** [comment] 2021-11-09 17:25
I will think about this use case and provide some solution in one of the future releases. Thank you for this suggestion!

**Comment by MarcinZiabek** [comment] 2022-01-31 00:18
This feature was introduced in the [QuestPDF 2022.02 release](https://www.questpdf.com/documentation/api-reference.html#stop-paging) 😁 Closing

**Closed by MarcinZiabek** 2022-01-31 00:18 UTC

**Comment by blogcraft** [comment] 2023-06-30 19:04
I know this problem has been fixed for that use case. But I find myself in a similar but not same situation.

I Use a lot of tables, and sometimes my colum with is fixed to certain width but the text is wider than the cell.

The thing is, that currently the text wraps into a second row inside the cell, and I want to prevent that.

Now:

+--------------------+
|My Normal Text      |
+--------------------+

With large text:
+--------------------+
|My Extremely large |
|Text                         |
+--------------------+

What Would I like to have:
+--------------------+
|My Extremely larg.. |
+--------------------+

**Comment by MarcinZiabek** [comment] 2023-07-03 15:10
> I know this problem has been fixed for that use case. But I find myself in a similar but not same situation.
> 
> I Use a lot of tables, and sometimes my colum with is fixed to certain width but the text is wider than the cell.
> 
> The thing is, that currently the text wraps into a second row inside the cell, and I want to prevent that.
> 
> Now:
> 
> ```
> +--------------------+
> |My Normal Text      |
> +--------------------+
> ```
> 
> With large text:
> 
> ```
> +--------------------+
> |My Extremely large  |
> |Text                |
> +--------------------+
> ```
> 
> What Would I like to have:
> 
> ```
> +--------------------+
> |My Extremely larg...|
> +--------------------+
> ```

[The StopPaging element](https://www.questpdf.com/api-reference/stop-paging.html) should help in most cases. However, it will not put an ellipsis at the end of the text.
