### ISSUE TITLE
Document that QuestPDF.Settings.DocumentLayoutExceptionThreshold is counting Pages

### ISSUE THREAD

**Issue by kirides** [QuestPDF/QuestPDF#428] opened 2022-12-07 14:29 UTC
**Is your feature request related to a problem? Please describe.**
`QuestPDF.Settings.DocumentLayoutExceptionThreshold` What is the limit for? Apples, bananas? Bytes? Characters? Seconds? Pages?

**Describe the solution you'd like**
A clear and concise description of what this property does.

**Describe alternatives you've considered**
There is no documentation

**Comment by girlpunk** [comment] 2022-12-07 16:10
https://www.questpdf.com/concepts/settings#maximum-document-length

**Comment by kirides** [comment] 2022-12-07 22:07
> https://www.questpdf.com/concepts/settings#maximum-document-length

sadly this part of the documentation does not tell _what_ counts towards "document length"

> Maximum document length[#](https://www.questpdf.com/concepts/settings#maximum-document-length)
This value represents the maximum length of the document that the library produces. This is useful when layout constraints are too strong, e.g. one element does not fit in another. In such cases, the library would produce document of infinite length, consuming all available resources. To break the algorithm and save the environment, the library breaks the rendering process after reaching specified length of document.

> 
> If your content requires generating longer documents, please assign the most reasonable value.

> 
> ```csharp
> QuestPDF.Settings.DocumentLayoutExceptionThreshold = 250;
> ```

Is it length in ... ?
- pages
- characters (do unicode characters count as more characters even though they take roughly the same space)
- bytes

`DocumentLayoutExceptionThreshold ` is a terrible name for this. At first glance i assumed it would be the amount of milliseconds the generation of a document must not exceed. And the libraries in-code documentation doesn't tell a thing

**Comment by MarcinZiabek** [comment] 2022-12-07 22:54
This parameter refers to the length of a document, counted in pages, so by default it is 250 pages long. When the generated number of pages exceeds that threshold, a proper exception is thrown that makes it rather clear:

```csharp
$"Composed layout generates infinite document. This may happen in two cases. " +
$"1) Your document and its layout configuration is correct but the content takes more than {Settings.DocumentLayoutExceptionThreshold} pages. " +
$"In this case, please increase the value {nameof(QuestPDF)}.{nameof(Settings)}.{nameof(Settings.DocumentLayoutExceptionThreshold)} static property. " +
$"2) The layout configuration of your document is invalid. Some of the elements require more space than is provided." +
$"Please analyze your documents structure to detect this element and fix its size constraints.";
```

I agree that the name of this property could be better, and that the documentation could clearly describe its purpose and used units. Quality is something that can be iteratively improved. Trust me, writing great documentation isn't easy, especially when things obvious to the creator, are not obvious to new users. I will take a note to improve this area somewhere in the future, thank you 😊

Most likely it is just a long hard day, and me being simply tired, but I have an impression that your comment isn't very friendly. Please try to be more polite next time, otherwise some may not take your comments very seriously. That being said, have a great day 😁

**Comment by kirides** [comment] 2022-12-08 09:25
i didn't mean to be rude :/

And thanks for the response!

I had a very lenthy discussion with a colleague about code/doc quality in our codebase and we came across some code snippet that used this property (because it was marked as deprecated after we updated and build failed due to warning), obviously the developer didn't know what the properly really did and used it in a wrong way.

**Comment by girlpunk** [comment] 2022-12-08 11:55
@kirides Apologies if my initial comment came across as rude too. Unfortunately like many open source projects there are a number of "bugs" reported that are simply caused by users not reading the documentation, and I (clearly incorrectly) assumed this was one.

**Comment by MarcinZiabek** [comment] 2023-01-10 11:23
I am going to adjust the documentation to better describe the unit of the `QuestPDF.Settings.DocumentLayoutExceptionThreshold` setting. This small improvement will be part of the 2022.12.1 release.

@kirides Thank you for this suggestion 😁

**Closed** 2023-04-16 22:02 UTC
