### ISSUE TITLE
System.AccessViolationException thrown while generating PDF

### ISSUE THREAD

**Issue by VicZhang1** [QuestPDF/QuestPDF#232] opened 2022-05-25 09:05 UTC
**Describe the bug**
I am choosing a open source software for PDF, QuestPDF looks very good. I create a WPF project based on .Net Framework 4.6 and try to generate a PDF document, but I get an exception `System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`. 

**To Reproduce**
2022.5.0 QuestPDF installed with following code:
```
var document = Document.Create(container =>
                {
                    container.Page(descriptor =>
                    {
                        descriptor.Header()
                           .Text("Hello PDF!")
                           .SemiBold().FontSize(36).FontColor(QuestPDF.Helpers.Colors.Blue.Medium);
                    });
                });

                var metaData = document.GetMetadata();
                metaData.Author = "Demo";
                document.WithMetadata(metaData);

                document.GeneratePdf(fileName);
```
the exception is thrown on `document.GeneratePdf(fileName);`

**Expected behavior**
PDF generated successfully.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by VicZhang1** [comment] 2022-05-25 11:00
After downgrading the version of QuestPDF to `2022.4.1`, it works fine.

**Comment by MarcinZiabek** [comment] 2022-05-25 12:37
I don't see any specific reason why the newer version does not work. Are you sure that the file location was not taken by other process? Or something similar? Would you like to check if this is repeatable with other paths or file names?

**Comment by sliceofbytes** [comment] 2022-06-06 21:48
I'm also having the same issue, and reverting to previous version did not help.

**Comment by MarcinZiabek** [comment] 2022-06-06 23:03
@sliceofbytes  Would you like to create a repository that could be used to reproduce the issue? Best, with details about environment where the code is run 😁

**Comment by sliceofbytes** [comment] 2022-06-07 14:32
Hey It is running in a .Net Framework 4.6.7 Class library.

My colleague was able to track down the issue by reverting to a working version and slowly adding back the code changes.

The offending code was:

`t.Cell().Border(1).BorderColor(Colors.Grey.Lighten1).Height(2, Unit.Inch).Padding(5);`

Fixed by adding an empty text node.

`t.Cell().Border(1).BorderColor(Colors.Grey.Lighten1).Height(2, Unit.Inch).Padding(5).Text("");`

**Comment by sliceofbytes** [comment] 2022-06-07 15:26
I spoke too soon on this issue. We are able to trigger this error by causing the following line to wrap. Interestingly enough it does still write the PDF, If reduce the length of the text so it does not wrap the exception is not thrown.

Only change we are making that is causing a crashing build vs a not crashing build is the text in ticket.Title.

```csharp

l.PrimaryLayer().Padding(maxBleed,Unit.Inch).MinimalBox().Width(ticketAreaEffectiveWidth,Unit.Inch).Height(ticketAreaEffectiveHeight,Unit.Inch).Border(1).BorderColor("#FF0000").Text(ticket.Title);
```


Any advise would be greatly appreciated. Unfortunately we are on a crush right now so I don't have time to repro this.

**Comment by MarcinZiabek** [comment] 2022-06-08 00:45
@sliceofbytes Would you be able to provide the full stack trace of this exception? I am trying to locate the source of the exception, no luck so far...

Also, please try using the QuestPDF 2022.6-prerelease version (make sure to enable the prerelease checkbox in your IDE).

**Comment by SparkyTD** [comment] 2024-03-15 19:35
This issue still exists on version 2024.3.0-beta, but it's not consistent. If I run the same generator code ten times, about three of them will crash the entire application with this unrecoverable exception. [Here's](https://pastebin.com/raw/TGBpNyRs) my full stack trace.

**Comment by AndreasKl** [comment] 2024-06-17 14:15
We currently see this issue on our CI system with **QuestPDF 2024.3.10**. OS is a mcr.microsoft.com/dotnet/sdk:8.0-**windowsservercore-ltsc2019** container:


```
 Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at QuestPDF.Skia.Text.SkParagraph+API.paragraph_plan_layout(IntPtr, Single)
--------------------------------
   at QuestPDF.Skia.Text.SkParagraph.PlanLayout(Single)
   at QuestPDF.Elements.Text.TextBlock.CalculateParagraphMetrics(QuestPDF.Infrastructure.Size)
   at QuestPDF.Elements.Text.TextBlock.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Elements.Padding.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Elements.Column.PlanLayout(QuestPDF.Infrastructure.Size)
   at QuestPDF.Elements.Column.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Elements.DynamicContext.CreateElement(System.Action`1<QuestPDF.Infrastructure.IContainer>)
   at nom.BackgroundWorker.ScheduledJobs.PasswordLetter.SignatureLetterDocument+HeaderContent.Compose(QuestPDF.Elements.DynamicContext)
   at QuestPDF.Elements.DynamicHost.GetContent(QuestPDF.Infrastructure.Size, Boolean)
   at QuestPDF.Elements.DynamicHost.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Elements.Decoration.<PlanLayout>g__GetDecorationMeasurement|20_0(QuestPDF.Infrastructure.Element, <>c__DisplayClass20_0 ByRef)
   at QuestPDF.Elements.Decoration+<PlanLayout>d__20.MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at QuestPDF.Elements.Decoration.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Elements.Padding.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Elements.Constrained.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Elements.Layers.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Infrastructure.ContainerElement.Measure(QuestPDF.Infrastructure.Size)
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](QuestPDF.Infrastructure.PageContext, System.__Canon, QuestPDF.Infrastructure.ContainerElement)
   at QuestPDF.Drawing.DocumentGenerator.RenderSingleDocument[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, QuestPDF.Infrastructure.IDocument, QuestPDF.Infrastructure.DocumentSettings)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, QuestPDF.Infrastructure.IDocument, QuestPDF.Infrastructure.DocumentSettings)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(QuestPDF.Skia.SkWriteStream, QuestPDF.Infrastructure.IDocument)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(QuestPDF.Infrastructure.IDocument)
```

**Comment by MarcinZiabek** [comment] 2024-06-17 15:05
@AndreasKl Thank you for sharing this issue 😄 I would highly appreciate code that reproduces this issue, and any additional context/observations that could be helpful in resolving it as soon as possible.

**Comment by AndreasKl** [comment] 2024-07-10 09:19
@MarcinZiabek Sorry for the delay, we were not able to reproduce the issue. Meanwhile we also updated the libary, so feel free to close the ticket.

**Comment by MarcinZiabek** [comment] 2024-07-16 08:33
No worries 😄  

I am closing this issue. In case of any similar problems, please feel free to create a new issue.

**Closed by MarcinZiabek** 2024-07-16 08:33 UTC
