### ISSUE TITLE
Sometimes Row Separator is not shown properly when Table spans multiple pages

### ISSUE THREAD

**Issue by harvinders** [QuestPDF/QuestPDF#117] opened 2022-02-06 23:57 UTC
**Describe the bug**
Sometime when I am generating table, separator lines between two rows don't show up properly on the next page. Please see the top of table at page 2 in the screenshot for an example.

**To Reproduce**
The code that generates the table follows

```cs
        public void Compose(IContainer container)
        {
            var headerStyle = TextStyle.Default.SemiBold();
            container.Column(column =>
            {
                column.Item().Text(Title, Typography.Headline.SemiBold());
                column.Spacing(10);
                column.Item()
                    .PaddingBottom(20)
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.ConstantColumn(25);
                            columns.RelativeColumn(3);
                            columns.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("#", headerStyle);
                            header.Cell().Text("Test", headerStyle);
                            header.Cell().Text("Result", headerStyle);

                            header.Cell().ColumnSpan(3).PaddingVertical(5).BorderBottom(1).BorderColor("#1788C3");
                        });

                        foreach (var item in MethodResults)
                        {
                            table.Cell().Text(MethodResults.IndexOf(item) + 1);
                            table.Cell().Text(item.Name);
                            table.Cell().Text($"{item.Result}",
                                item.Result == "Failed" ? Typography.Error : Typography.Normal);

                            table.Cell().ColumnSpan(3).PaddingVertical(5).LineHorizontal(1).LineColor("#d1e7f3");
                        }
                    });
            });
        }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8557046/152706940-b17591da-39cf-4468-bde0-d905adc69382.png)

**Comment by MarcinZiabek** [comment] 2022-02-07 21:17
Hello 😊 Thank you for finding this issue. I am afraid that... the library works correctly in this case. The line is placed in a separate row and therefore, in some cases, is pushed to the next page. So the problem is within the badly designed example (my fault).

Let me give you an improved code (an update official documentation in a minute)😁

```csharp
foreach (var item in MethodResults)
{
    table.Cell().Element(CellStyle).Text(MethodResults.IndexOf(item) + 1);
    table.Cell().Element(CellStyle).Text(item.Name);
    table.Cell().Element(CellStyle).Text($"{item.Result}", item.Result == "Failed" ? Typography.Error : Typography.Normal);

    static IContainer CellStyle(IContainer container) => container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(5);
}
```

**Comment by MarcinZiabek** [comment] 2022-05-11 22:08
Proper fix for this issues was found and the documentation was updated a while ago. Closing 😁

**Closed by MarcinZiabek** 2022-05-11 22:08 UTC
