### ISSUE TITLE
Streaming output due to high memory consumption

### ISSUE THREAD

**Issue by kl1mm** [QuestPDF/QuestPDF#816] opened 2024-03-13 10:33 UTC
**Is your feature request related to a problem? Please describe.**
Unfortunately, due to the law, we have very large tables that our customers have to report. The data is not very complex, mainly long (multi-line) (legal) texts and figures. 
A concrete example is a table with 14 columns and up to 2,000,000 million rows. This results in approx. 65,000 pages.

When generating the PDF, we can see that the document is created completely in memory and the byte[] is then written to a file. In our case, it would be desirable if intermediate results could be written to the output file, or the data could even be written directly to a file stream. 

As the working memory runs out at some point, our systems start to swap with the data volumes described - which unfortunately has a major impact on speed.

**Describe the solution you'd like**
Write the generated bytes directly to a (file) stream. Or perhaps in blocks to free up memory again.

**Describe alternatives you've considered**
It may be possible to render the large table into several documents (perhaps even in parallel) and merge them later. However, it is not clear to us how to "keep the table together", especially since the order of the rows is relevant for legal reporting

**A**Additional context**
We are currently testing QuestPDF and it would be great if we could implement all our requirements with it. It's a great library and looks very promising

**Comment by MarcinZiabek** [comment] 2024-03-14 09:29
Thank you for creating this issue and sharing your experience.

I agree that improving performance and minimizing memory consumption are essential and on the roadmap. I am dedicated to working on such enhancements over the following months, targeting various improvements iteratively.

Would you please share more about your document layout (e.g., layout screenshots/code) and the memory demand you are observing? What values would be acceptable, in your opinion?

**Comment by kl1mm** [comment] 2024-03-14 11:31
Hi [MarcinZiabek](https://github.com/MarcinZiabek),
I have tried to separate the document into a small example:
For simplicity, we have minimized the data for the example and serialized it into a json file.
In the Document generation we use the Linq.Take to "only" run 50.000 rows wich results in:

Document created in 00:00:00.0035442
Pdf created in 00:01:09.7197666
Approximate memory usage: 12446 MB

"output.pdf"  => 75 MB (12.000 pages)

<details>
  <summary>Program.cs</summary>

```csharp
var model = System.Text.Json.JsonSerializer.Deserialize<DataModel>(File.ReadAllText(@"C:\_tmp\x.json"))!.Prepare();

QuestPDF.Settings.License = LicenseType.Community;
QuestPDF.Settings.EnableDebugging = false;
QuestPDF.Settings.EnableCaching = true;

var timestamp = Stopwatch.GetTimestamp();
var document = new DR1_Document(model).CreateDocument();
Console.WriteLine($"Document created in {Stopwatch.GetElapsedTime(timestamp)}");

timestamp = Stopwatch.GetTimestamp();
document.GeneratePdf("output.pdf"); 
Console.WriteLine($"Pdf created in {Stopwatch.GetElapsedTime(timestamp)}");

using Process proc = Process.GetCurrentProcess();
Console.WriteLine($"Approximate memory usage: {proc.PrivateMemorySize64 / (1024*1024)} MB");
```

</details>

<details>
  <summary>DR1_Document.cs</summary>

```csharp
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace kli.DR1;

public class DR1_Document(DataModel model)
{
    public IDocument CreateDocument() =>
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.DefaultTextStyle(ts => ts.FontFamily("Arial"));
                page.Size(PageSizes.A4.Landscape());
                page.MarginTop(16);
                page.MarginHorizontal(32);

                page.Header().PaddingBottom(40).Element(ComposeHeader);
                page.Content().Element(ComposeContent);
                page.Footer().Height(60);
            });
        });

    private void ComposeContent(IContainer container)
    {
        var textStyle = TextStyle.Default.FontSize(7);
        var cellTextStyle = TextStyle.Default.FontSize(6).LineHeight(1.1f);

        container.Column(column =>
        {
            column.Item().Row(row =>
                row.RelativeItem().Text("Selection: Free selection").Style(textStyle));
            column.Item().Row(row =>
                row.RelativeItem().Text("Registration: 01/01/2020 to 30/06/2020").Style(textStyle));
            column.Item().Row(row =>
            {
                row.RelativeItem().Table(table =>
                {
                    IContainer DefaultCellStyle(IContainer con) =>
                        con.Element(c => c.DefaultTextStyle(textStyle))
                            .BorderVertical(.5f)
                            .BorderColor(Colors.Black)
                            .PaddingVertical(1)
                            .PaddingHorizontal(5)
                            .AlignTop();
            
                    table.Header(HeaderCells());
                    table.ColumnsDefinition(ColumnDefs());
            
                    foreach (var dataRow in model.FieldRows.Take(50_000)) // Take(). for testing   
                    {
                        table.Cell().Element(CellStyle).Text(dataRow.FieldStrValues[0]);
                        table.Cell().EnsureSpace().Element(CellStyle).Text(dataRow.FieldStrValues[1]);
                        table.Cell().Element(CellStyle).AlignRight().Text(dataRow.FieldStrValues[2]);
                        table.Cell().Element(CellStyle).AlignRight().Text(dataRow.FieldStrValues[3]);
                        table.Cell().Element(CellStyle).Text(dataRow.FieldStrValues[4]);
                        table.Cell().Element(CellStyle).AlignRight().Text(dataRow.FieldStrValues[5]);
                        table.Cell().Element(CellStyle).Text(dataRow.FieldStrValues[6]);
                        table.Cell().Element(CellStyle).Text(dataRow.FieldStrValues[7]);
                        table.Cell().Element(CellStyle).AlignRight().Text(dataRow.FieldStrValues[8]);
                        table.Cell().Element(CellStyle).AlignCenter().Text(dataRow.FieldStrValues[9]);
                        table.Cell().Element(CellStyle).Text(dataRow.FieldStrValues[10]);
                        table.Cell().Element(CellStyle).AlignRight().Text(dataRow.FieldStrValues[11]);
                        table.Cell().Element(CellStyle).Text(dataRow.FieldStrValues[12]);
                        table.Cell().Element(CellStyle).Text(dataRow.FieldStrValues[13]);
                    }
 
                    IContainer CellStyle(IContainer c) => DefaultCellStyle(c).Element(e => e.DefaultTextStyle(cellTextStyle));
                });
            });
        });
    }

    private static Action<TableCellDescriptor> HeaderCells() =>
        header =>
        {
            var textStyle = TextStyle.Default.FontSize(7);
            header.Cell().ColumnSpan(10).BorderHorizontal(1).Element(Style).AlignCenter().Text("Designation of the cover value");
            header.Cell().ColumnSpan(3).BorderHorizontal(1).Element(Style).AlignCenter().Text("Deletion");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text(" ");

            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("1");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("2a");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("2b");
            header.Cell().ColumnSpan(3).BorderHorizontal(1).Element(Style).AlignCenter().Text("3");
            header.Cell().ColumnSpan(4).BorderHorizontal(1).Element(Style).AlignCenter().Text("4");
            header.Cell().ColumnSpan(3).BorderHorizontal(1).Element(Style).AlignCenter().Text("5");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("6");
                        
            header.Cell().RowSpan(2).BorderHorizontal(1).Element(Style).Text("a) No. b) AZ \\r\\nc) Date");
            header.Cell().RowSpan(2).BorderHorizontal(1).Element(Style).AlignCenter().Text("Designation of the encumbered property or the right equivalent to real property");
            header.Cell().RowSpan(2).BorderHorizontal(1).Element(Style).AlignCenter().Text("Mortgage lending values at the time of taking up cover");
            header.Cell().ColumnSpan(3).BorderHorizontal(1).Element(Style).AlignCenter().Text("Urgent security (mortgage)");
            header.Cell().ColumnSpan(4).BorderHorizontal(1).Element(Style).AlignCenter().Text("Secured personal claim(s)\\r\\n(dispensable in the case of mortgage)\\r\\na), b) etc.");
            header.Cell().RowSpan(2).BorderHorizontal(1).Element(Style).AlignCenter().Text("Column number of the entry to be deleted");
            header.Cell().RowSpan(2).BorderHorizontal(1).Element(Style).AlignCenter().Text("Amount");
            header.Cell().RowSpan(2).BorderHorizontal(1).Element(Style).AlignCenter().Text("Date Signature");
            header.Cell().RowSpan(2).BorderHorizontal(1).Element(Style).AlignCenter().Text("Remark");
                        
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("No. in section III");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("Currency");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("Nominal amount");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("Debtor");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("Currency");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("Amount");
            header.Cell().BorderHorizontal(1).Element(Style).AlignCenter().Text("Darl.");

            IContainer Style(IContainer c) 
                => c.Element(c1 => c1.DefaultTextStyle(textStyle.Bold()))
                    .BorderVertical(.5f)
                    .BorderColor(Colors.Black)
                    .PaddingVertical(1)
                    .PaddingHorizontal(5)
                    .AlignTop();
        };

    private static Action<TableColumnsDefinitionDescriptor> ColumnDefs() =>
        columns =>
        {
            columns.RelativeColumn(1.5f);
            columns.RelativeColumn(3.25f);
            columns.RelativeColumn(2.4f);
            columns.RelativeColumn(.92f);
            columns.RelativeColumn();
            columns.RelativeColumn(2);
            columns.RelativeColumn(2.5f);
            columns.RelativeColumn();
            columns.RelativeColumn(2);
            columns.RelativeColumn(1.5f);
            columns.RelativeColumn(1.7f);
            columns.RelativeColumn(2);
            columns.RelativeColumn();
            columns.RelativeColumn();
        };

    private void ComposeHeader(IContainer container)
    {
        var titleStyle = TextStyle.Default.FontSize(16).ExtraBold();
        var textStyle = TextStyle.Default.FontSize(10);

        container.Column(column =>
        {
            column.Item().PaddingBottom(8).Row(row => { row.RelativeItem().Text("Institute").Style(titleStyle); });
            column.Item().Row(row => { row.RelativeItem().Text("Mortgage cover register").Style(titleStyle); });
            column.Item().Row(row =>
            {
                row.RelativeItem().AlignRight().Element(x => x.DefaultTextStyle(textStyle)).Text(x =>
                {
                    x.Span("Site ");
                    x.CurrentPageNumber();
                    x.Span(" / ");
                    x.TotalPages();
                });
            });
            column.Item().Row(row =>
            {
                row.RelativeItem().Text("The following sub-registers are kept as components of the cover register:").Style(textStyle);
                row.RelativeItem().AlignRight().Text("Date of data retrieval: 03/02/2024").Style(textStyle);
            });
            column.Item().Row(row => { row.RelativeItem().Text("Sub-register for assets in accordance with Section 14 DeckReckV (see report sheet Sub-register DR Mortgages)").Style(textStyle); });
        });
    }
}
```
</details>

Our document is certainly anything but good in terms of optimization and of course we are grateful for any advice on how we can make it better.



<details>
  <summary>Here is a screenhot how it lookslike:</summary>

![Screenshot_DR_1](https://github.com/QuestPDF/QuestPDF/assets/18304813/75be39a4-cfdc-4d6c-974b-6c26287d0750)

</details>

All in all, it just seems a lot when 12 GB of memory is used for a document that is 75 MB in size.
It is difficult to say what we find acceptable. We are grateful for any form of optimization.
Perhaps you only need to take a look at our document structure to find out that we are not using it optimally.

I hope I was able to make things a little clearer with this example.

Thanks and best regards

**Comment by MarcinZiabek** [comment] 2024-03-26 06:55
I would like to confirm the higher-than-expected memory consumption, especially in the 2024.3.0 release. It is primarily related to unmanaged memory taken by Skia. I have a couple of ideas for significantly improving memory resource utilization, and it will be my highest priority in the next release.

@kl1mm Thank you very much for presenting this issue. I completely agree with you that this is an area that should be investigated and improved.

**Comment by kl1mm** [comment] 2024-03-26 07:27
Morning guys,
@coverrt I have added further "PrintApproximateMemoryUsage" outputs to the example. And attached a screenshot, I hope it will answer your question? The .json document we load is around 100MB with (as u can see in the screenshot) around 220.000 entires.

<details>
<summary>Screenshot</summary>

![Screenshot 2024-03-26 081436](https://github.com/QuestPDF/QuestPDF/assets/18304813/b0f05917-f676-4cae-ab97-d401203788bb)

</details>

@MarcinZiabek we appreciate your efforts and hope to hear of your success as soon as possible. Let us know if we can provide any assistance.

Thanks and best regards

**Comment by MarcinZiabek** [comment] 2024-03-26 08:53
Sure thing! If you have time to check, would you please test how memory usage scales with content length? I wonder if there is some constant 1GB preallocation done by dotnet, even for tiny documents.

**Comment by kl1mm** [comment] 2024-03-27 08:44
Morning @MarcinZiabek ,
here are some numbers:

<details>
<summary>10_KB.json - 9 datarows</summary>

Program start: approximate memory usage: 7 MB
After deserialize dataModel: approximate memory usage: 7 MB
Document created in 00:00:00.0067518
After Document created: approximate memory usage: 8 MB
Pdf created in 00:00:00.1412866
After GeneratePdf: approximate memory usage: 34 MB
output.pdf -> 90 KB 
</details>

<details>
<summary>1_MB.json - 1.258 datarows</summary>

Program start: approximate memory usage: 7 MB
After deserialize dataModel: approximate memory usage: 19 MB
Document created in 00:00:00.0034332
After Document created: approximate memory usage: 20 MB
Pdf created in 00:00:02.2381184
After GeneratePdf: approximate memory usage: 335 MB
output.pdf -> 2 MB 
</details>

<details>
<summary>10_MB.json - 16.134 datarows</summary>

Program start: approximate memory usage: 7 MB
After deserialize dataModel: approximate memory usage: 128 MB
Document created in 00:00:00.0041961
After Document created: approximate memory usage: 128 MB
Pdf created in 00:00:22.3994339
After GeneratePdf: approximate memory usage: 3.086 MB
output.pdf -> 22 MB 
</details>

<details>
<summary>100_MB.json - 221.235 datarows</summary>

Program start: approximate memory usage: 7 MB
After deserialize dataModel: approximate memory usage: 1.432 MB
Document created in 00:00:00.0032863
After Document created: approximate memory usage: 1.433 MB
Pdf created in 00:07:42.2741724
After GeneratePdf: approximate memory usage: 39.713 MB
output.pdf -> 290 MB 
</details>

Best regards

**Comment by MarcinZiabek** [comment] 2024-03-27 08:49
Thank you so much! I highly appreciate your help ❤️  

It really seems to scale linearly. What version of QuestPDF were you using during testing? Unfortunately, the 2024.3.X has a regression in terms of peak memory usage. Enhancing resource utilization is my highest priority at this moment. I have some ideas for improving it, and I plan to release those enhancements within the 2024.5 release.

**Comment by kl1mm** [comment] 2024-03-27 09:00
Everything I did here was with the version: 2024.3.0-beta

**Comment by robertorp** [comment] 2024-05-06 22:29
I have the same problem, in my case I did the following simulation, but in practice I generate 4 columns and there are on average 500 pages

```
[HttpGet("imprimir-teste-ram")]
[AllowAnonymous]
[Produces("application/json")]
[ProducesResponseType(typeof(ValidationProblemDetails), 400)]
[ProducesResponseType(typeof(RetornaPdfBase64), 200)]
public async Task<IActionResult> GerarDanfe2()
{
    // Nome do arquivo PDF a ser gerado
    string pdfFileName = "exemplo.pdf";

    // code in your main method

    QuestPDF.Settings.License = LicenseType.Community;


    var _memoryStreamManager = new RecyclableMemoryStreamManager();
    _memoryStreamManager.Settings.BlockSize = 4096;
    _memoryStreamManager.Settings.LargeBufferMultiple = 1048576;
    _memoryStreamManager.Settings.MaximumLargePoolFreeBytes = 20 * 1048576; // 20
    _memoryStreamManager.Settings.MaximumSmallPoolFreeBytes = 50 * 1048576;
    _memoryStreamManager.Settings.MaximumBufferSize = 16 * 1048576; // 16 MB


    await using (var memoryStream = _memoryStreamManager.GetStream())
    {
        Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(20));

                    page.Header()
                        .Text("Hello PDF!")
                        .SemiBold().FontSize(36).FontColor(Colors.Blue.Medium);

                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            for (int i = 0; i < 10000; i++)
                            {
                                x.Spacing(20);

                                x.Item().Text(Placeholders.LoremIpsum());
                                x.Item().Image(Placeholders.Image(200, 100));
                            }
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Page ");
                            x.CurrentPageNumber();
                        });
                });
            })
            .GeneratePdf(memoryStream);

        UploadPDFToS3(pdfFileName, memoryStream);
    }

    return CustomResponse();
}
```

<PackageReference Include="QuestPDF" Version="2024.3.4" />

**Comment by MarcinZiabek** [comment] 2024-05-07 21:20
A couple of questions to help me understand the problem 😄 

Would you please share what memory usage you observed during your testing? 
Is it stable, or is there any memory leak? 
Are your documents rich in text? 
Are you using many text elements with relatively short content?
Is the high memory usage visible during generation, or right before populating the stream?

Please note that a larger portion of the native memory can be acquired at the beginning.

I have an idea on how to reduce memory usage by around 50-70% in large and text-rich documents.

**Comment by kl1mm** [comment] 2024-06-12 08:11
Hey @MarcinZiabek,
anything new here? You had indicated that you are planning the optimizations for 2024.5.0, I saw that you have created 2024.06?

Best regards

**Comment by MarcinZiabek** [comment] 2024-06-12 08:26
Indeed, the memory consumption enhancement has not been included in the current release due to other higher priority quality issues and tasks that needed attention. I apologize for the delay.

However, the latest version lays the crucial groundwork for implementing this enhancement. Moving forward, it will be my next priority 😄

**Comment by mariustoporascu** [comment] 2024-06-21 20:45
Hello, I was having the same issue(collection smaller tough, @ 20k rows), but I was restricted in terms of computing power, and after trying multiple solutions (Dynamic element too), I have reached the following procedure to keep mem consumption low:
1. Knowing the max number of possible rows to skip take from my collection
2. Try to generate pages with items up to page 1 completed or layout exception happened(i can't yet find a complete solution for this but it rarely happens too).
3. Regenerate last successful page and add the bytes to a collection.
4. Once I have all the pages I rely on another library(iTextSharp lgpl vers) to merge and paginate the doc.
This temporary solution might need improvements in terms of speed, but does the job. 
Also I have chosen to start the for loop from i = 1, but you can try to start higher.

Attached results on 18426 rows:


Attached code for reference:
`    
internal static class OpisGenerator
    {
        public static void GenerateV2(OpisContractDto data)
        {
            List<byte[]> docs = [];
			int maxChunkSize = 24;
			int start = 0;
			int totalCount = data.Owners.Count;
			while (start < totalCount)
			{
				int low = 1,
					high = maxChunkSize,
					currentChunkSize = 1;
				// Binary search for the optimal chunk size
				while (low <= high)
				{
					int mid = (low + high) / 2;
					var chunk = data.Owners.Skip(start).Take(mid).ToList();

					try
					{
						// Try to generate the PDF for the chunk
						GeneratePdfForChunk(chunk, data);
						currentChunkSize = mid; // If successful, update currentChunkSize
						low = mid + 1; // Try for a larger chunk
					}
					catch (Exception)
					{
						// If it fails, try smaller chunk
						high = mid - 1;
					}
				}

				// Generate PDF with the determined chunk size
				var finalChunk = data.Owners.Skip(start).Take(currentChunkSize).ToList();
				
				docs.Add(GeneratePdfForChunk(finalChunk, data));

				Console.WriteLine($"Chunk {start} - {start + currentChunkSize} generated");
				start += currentChunkSize;
			}

            // step : remove duplicated resources
            using var intermediateStream = new MemoryStream();
            var document = new iTextSharp.text.Document();
            using var copy = new PdfSmartCopy(document, intermediateStream);
            document.Open();

            foreach (var item in docs)
            {
                using var reader = new PdfReader(item.ToArray());

                // use PdfSmartCopy to remove duplicated resources
                for (int i = 1; i <= reader.NumberOfPages; i++)
                {
                    copy.AddPage(copy.GetImportedPage(reader, i));
                }
            }
            document.Close();
            // step : paginate document
            using var finalStream = new MemoryStream();
            using var fReader = new PdfReader(intermediateStream.ToArray());
            using var stamper = new PdfStamper(fReader, finalStream);
            for (int i = 1; i <= fReader.NumberOfPages; i++)
            {
                var content = stamper.GetOverContent(i);
                var font = BaseFont.CreateFont(
                    BaseFont.HELVETICA,
                    BaseFont.CP1252,
                    BaseFont.NOT_EMBEDDED
                );
                content.BeginText();
                content.SetFontAndSize(font, 8.5f);
                content.SetTextMatrix(0, 0);
                var pageSize = fReader.GetPageSize(i);
                content.ShowTextAligned(
                    Element.ALIGN_RIGHT,
                    $"Pagina {i} din {fReader.NumberOfPages}",
                    pageSize.Width - 30,
                    17,
                    0
                );
                content.EndText();
            }
            stamper.Close();
            File.WriteAllBytes("E:\\opis.pdf", finalStream.ToArray());
        }

        static byte[] GeneratePdfForChunk(List<OwnerOpisDto> chunk, OpisContractDto data)
        {
            var bytes = Document
                .Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Size(PageSizes.A4.Landscape());
                        page.DefaultTextStyle(x => x.FontSize(10).FontColor(Colors.Black));
                        page.MarginHorizontal(20);
                        page.MarginVertical(15);
                        page.PageColor(Colors.White);
                        page.Header().Element(x => ComposeHeader(x, data));
                        page.Content().Element(x => ComposeContent(x, chunk));
                        page.Footer().Element(x => ComposeFooter(x, data));
                    });
                })
                .GeneratePdf();
            using var reader = new PdfReader(bytes);
            if (reader.NumberOfPages > 1)
            {
                throw new Exception("Stop at page 1 generated");
            }

            return bytes;
        }
   ..... other code related to header,content,footer
   }
`

**Comment by MarcinZiabek** [comment] 2024-06-22 11:01
@kl1mm @mariustoporascu I am happy to share that the latest version of the QuestPDF library `2024.6.2` introduces a long-awaited optimization that significantly reduces memory usage when generating long documents rich in many Text elements. Based on the stress testing, it can reduce memory consumption by up to 95% while offering 10% improved generation performance. 

Could you please give it a try? https://github.com/QuestPDF/QuestPDF/releases/tag/2024.6.2

**Comment by mariustoporascu** [comment] 2024-06-23 17:56
@MarcinZiabek I can just say wow. Great job. 
Test with same data
Pdf created in 00:00:05.8284849
Approximate memory usage: 200 MB

**Comment by kl1mm** [comment] 2024-06-24 06:59
@MarcinZiabek,
I agree - well done 👍

I've looked up my example again and run it with the new QuestPDF version.
It hasn't gotten any faster (but it is already fast) but the memory consumption has dropped massively.
We will now plan when we can test it in our productive code :) Thank you for your efforts and maybe the streaming feature will come at some point :)

Best regards


100_MB.json - 221.235 datarows
Program start: approximate memory usage: 7 MB | **~same**
After deserialize dataModel: approximate memory usage: 1.432 MB | **~same**
Document created in 00:00:00.0032863 | **~same**
After Document created: approximate memory usage: 1.433 MB | **~same**
Pdf created in 00:07:42.2741724 | **~same**
After GeneratePdf: approximate memory usage: 39.713 MB |  _**approximate ~4.900 MB**_ 😮
output.pdf -> 290 MB | **~275 MB**

**Comment by MarcinZiabek** [comment] 2024-06-24 07:31
@kl1mm Nearly 8 minutes for PDF generation is much longer than I expected. Could you please profile your code? It would be best to use dotTrace with sampling profiling.

Does document creation involve any IO, such as a database queries, reading files, making HTTP requests, or connecting to external resources? 

Does your document have many images?

For your information, if you want to measure the document creation time, you may need to put the StopWatch class inside the Document.Create() lambda, as that function is lazy.

Thank you for testing 😄

**Comment by kl1mm** [comment] 2024-06-24 11:29
@MarcinZiabek,
I have profiled my sample for you. Attached is the snapshot:
[kli.DR1.zip](https://github.com/user-attachments/files/15954512/kli.DR1.zip)

Best regards

**Comment by MarcinZiabek** [comment] 2024-06-24 13:32
@kl1mm Is it possible that most of your Text elements are empty? Containing null, empty string or only whitespace characters?

**Comment by kl1mm** [comment] 2024-06-24 19:00
@MarcinZiabek, 

Yes, unfortunately that is the case. It is a layout with many columns as required by law. In most cases, however, only a few are filled per line, depending on the data of course.

**Comment by MarcinZiabek** [comment] 2024-06-25 04:43
I wasn't aware that empty Text could be such a common scenario. In https://github.com/QuestPDF/QuestPDF/commit/65d7c645cce1fe0d58ed883299ab697070acb911, I have introduced a cache that should shorten the generation time of your document by around 35% 😄

**Comment by MarcinZiabek** [comment] 2024-06-25 10:31
I have just released the `2024.6.4` version; please feel free to test 😄

**Comment by kl1mm** [comment] 2024-06-25 12:08
@MarcinZiabek,
here we go: Pdf created in 00:07:42.2741724 |  **_00:05:40.5502702_**
~ 25% improvment - wow 😮👍 

Thanks a lot 💋

**Comment by MarcinZiabek** [comment] 2024-06-25 15:01
Perfect! It looks much better. 😄

**Comment by kl1mm** [comment] 2024-06-25 15:05
For us the Results a fine for the moment, we really appriciate your work @MarcinZiabek.
Should I close the Issue?

**Comment by MarcinZiabek** [comment] 2024-06-25 15:13
If the current state of the library is sufficient for your workflow, please close the issue. I don't foresee any significant memory usage optimizations in the upcoming future. The closest effort that could help will be merging already existing PDF files, that I am hoping to introduce in late Q4 2024.

**Closed** 2024-06-25 15:14 UTC
