### ISSUE TITLE
Page Numbering in Footer Wraps across multiple pages despite having room - 

### ISSUE THREAD

**Issue by mark-hopper** [QuestPDF/QuestPDF#123] opened 2022-02-16 12:07 UTC
**Describe the bug**
When setting up a document that has a footer, which contains an image in the left hand corner, and text in the right-hand corner (in the form PAGE X of Y) which is a right aligned text block provided by lambda, it doesn't always fit it on the same page (it overflows into the next page's footer)

**To Reproduce**

```
public void Compose(IDocumentContainer container)
        {
            container
                .Page(page =>
                {
                    page.Margin(50);

                    page.Footer()
                        .Element(ComposeFooter);
                });
        }
```

```
private void ComposeFooter(IContainer container)
        {
            container.Row(row =>
            {
                row.ConstantItem(58)
                    .Image(
                        Placeholders.Image((int)58, 20));

                row.RelativeItem()
                    .DebugArea()
                    .AlignRight()
                    .Text(x =>
                    {
                        x.Span("PAGE ");
                        x.CurrentPageNumber();
                        x.Span(" OF ");
                        x.TotalPages();
                    });
            });
        }
```

**Expected behavior**
Because there's plenty of space provided for the text element, I would expect that the right alignment would correctly calculate the text's position such that it's full visible on the page.

**Screenshots**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/95866208/154260994-3db0b7ac-fd7e-4f9b-9707-95da76026195.png">

**Additional context**
I've tried using ShowEntire() which appears to have no effect. I wonder if this is because of the fact the text is provided by lambda, and is comprised of multiple text spans? As soon as I remove the Text Alignment this issue goes away, but it is a requirement of the document I'm generating for the page numbering to be in the right hand corner. If it was possible to be given direct access to the Page Number and Total Pages, I could use a single span with format strings that "may" get around this issue?

In case this is also a factor, I am using a custom font for this use-case, but for simplicity removed it from the code example.

**Comment by MarcinZiabek** [comment] 2022-02-16 14:36
What version exactly are you using? I copied your code and got the following results (2022.2.3):

![image](https://user-images.githubusercontent.com/9263853/154286450-10ee9656-b098-4568-8ded-7f2ddc1a6a0e.png)

**Comment by mark-hopper** [comment] 2022-02-16 14:38
Hi @MarcinZiabek thanks for getting back to me so quickly! I'm also running 2022.2.3 within the solution that generated that screenshot ... perhaps it is the custom font that's driving it's behaviour then?

**Comment by MarcinZiabek** [comment] 2022-02-16 14:47
I even tried to generate multiple pages with random content. All 50 pages have been rendered correctly.

What font it is exactly? Are you able to provide a minimal code example (repository) so I can reproduce the issue?

**Comment by mark-hopper** [comment] 2022-02-16 14:51
It's a customer built font set that I am using (therefore I'm not 100% if I can share the font with you), but I'll see if it's possible and get a minimal repro together for you

**Comment by mark-hopper** [comment] 2022-02-16 15:14
Small repro added here:
https://github.com/mark-hopper/QuestPDF-123/

Added you as collaborator so you can get access to the code. Running that sample results in the same behaviour as previously described.

**Comment by MarcinZiabek** [comment] 2022-02-16 15:30
There's something wrong with your code. It does not open correctly (within Rider).

**Comment by MarcinZiabek** [comment] 2022-02-16 15:47
Over next days I will do my best to analyse your example come with a proper fix. Thank you 😁

**Comment by MarcinZiabek** [comment] 2022-02-17 10:29
Thank you for finding this issue. Now I understand the root cause 😁 You are experiencing a very specific corner case connected to floating numbers arithmetic. 

I will try my best to provide fix today / tomorrow.

**Comment by mark-hopper** [comment] 2022-02-17 10:31
Not a problem ... I figured this was most likely a rounding or arithmetic inaccuracy somewhere along the line. And thank you that's much appreciated :)

**Comment by MarcinZiabek** [comment] 2022-02-17 10:54
The biggest problem it is inside the SkiaSharp library where the addition and comparison happens in this case. This is NOT SkiaSharp fault, just default behavior. So I need to take extra step somewhere around calling SkiaSharp text measure API.

**Comment by MarcinZiabek** [comment] 2022-02-18 20:56
Hello 😁 I have just published the 2022.2.4 release that fixes this issue. Please check if it solves your problem.

**Comment by mark-hopper** [comment] 2022-02-18 20:59
Hi @MarcinZiabek many thanks for this, I’ll try and have a look at this at the weekend and get back to you. I may be raising another issue regarding inconsistent border thicknesses but I’ll double check this with the new release before I do so.

**Comment by MarcinZiabek** [comment] 2022-02-21 13:59
Thank you for finding this corner case and confirming that the issue is fixed. Closing.

**Closed by MarcinZiabek** 2022-02-21 13:59 UTC
